id: PD4035CC7
initial_creation_type: input
source_metadata:
  title: Ratna Lingpa Series
  language: bo
  description: 'Texts by the famous treasure-revealer Ratna Lingpa (ratna gling pa,
    1403-1479):'
  volume:
    f8a20d0bb3e2436b9f735de22e8f817b:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Guru Padmasambhava
    f2df9f2d8ece433c9cf5c052ce362034:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      parent: Guru Padmasambhava
    b949bec6c0374c8a869c0029ba538df7:
      title: Aspiration Prayer from Tārā Sādhana
      parent: Tārā
created_at: '2022-03-01T01:19:45.928466'
last_modified_at: '2022-03-01T01:19:45.928469'
statistics:
  total_words: 2839
  total_non_words: 217
quality:
  non_words_ratio: 0.08
